# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formCliente(object):
    def setupUi(self, formCliente):
        formCliente.setObjectName("formCliente")
        formCliente.resize(545, 410)
        self.bt_adicionar = QtWidgets.QPushButton(formCliente)
        self.bt_adicionar.setGeometry(QtCore.QRect(10, 0, 81, 81))
        self.bt_adicionar.setText("")
        self.bt_adicionar.setObjectName("bt_adicionar")
        self.bt_alterar = QtWidgets.QPushButton(formCliente)
        self.bt_alterar.setGeometry(QtCore.QRect(90, 0, 81, 81))
        self.bt_alterar.setText("")
        self.bt_alterar.setObjectName("bt_alterar")
        self.bt_consultar = QtWidgets.QPushButton(formCliente)
        self.bt_consultar.setGeometry(QtCore.QRect(170, 0, 81, 81))
        self.bt_consultar.setText("")
        self.bt_consultar.setObjectName("bt_consultar")
        self.bt_excluir = QtWidgets.QPushButton(formCliente)
        self.bt_excluir.setGeometry(QtCore.QRect(250, 0, 81, 81))
        self.bt_excluir.setText("")
        self.bt_excluir.setObjectName("bt_excluir")
        self.bt_retornar = QtWidgets.QPushButton(formCliente)
        self.bt_retornar.setGeometry(QtCore.QRect(450, 0, 81, 81))
        self.bt_retornar.setText("")
        self.bt_retornar.setObjectName("bt_retornar")
        self.bt_pesquisarGeral = QtWidgets.QPushButton(formCliente)
        self.bt_pesquisarGeral.setGeometry(QtCore.QRect(450, 120, 31, 31))
        self.bt_pesquisarGeral.setStyleSheet("image:url(:/icon_geral/icons/filtro.png)")
        self.bt_pesquisarGeral.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_geral/icons/filtro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_pesquisarGeral.setIcon(icon)
        self.bt_pesquisarGeral.setObjectName("bt_pesquisarGeral")
        self.bt_pesquisar = QtWidgets.QPushButton(formCliente)
        self.bt_pesquisar.setGeometry(QtCore.QRect(410, 120, 31, 31))
        self.bt_pesquisar.setStyleSheet("image:url(:/icon_pesquisar/icons/pesquisar.png)")
        self.bt_pesquisar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon_pesquisar/icons/pesquisar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_pesquisar.setIcon(icon1)
        self.bt_pesquisar.setObjectName("bt_pesquisar")
        self.tb_cliente = QtWidgets.QTableWidget(formCliente)
        self.tb_cliente.setGeometry(QtCore.QRect(10, 210, 531, 192))
        self.tb_cliente.setObjectName("tb_cliente")
        self.tb_cliente.setColumnCount(4)
        self.tb_cliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(3, item)
        self.nome_cliente = QtWidgets.QLabel(formCliente)
        self.nome_cliente.setGeometry(QtCore.QRect(10, 130, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nome_cliente.setFont(font)
        self.nome_cliente.setObjectName("nome_cliente")
        self.lineEdit = QtWidgets.QLineEdit(formCliente)
        self.lineEdit.setGeometry(QtCore.QRect(100, 130, 291, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(formCliente)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 61, 51))
        self.label_2.setStyleSheet("image:url(:/icon_adicionar/icons/adicionar.png)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(formCliente)
        self.label_3.setGeometry(QtCore.QRect(100, 10, 61, 51))
        self.label_3.setStyleSheet("image:url(:/icon_alterar/icons/alterar.png)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(formCliente)
        self.label_4.setGeometry(QtCore.QRect(180, 10, 61, 51))
        self.label_4.setStyleSheet("image:url(:/icon_consultar/icons/consultar.png)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(formCliente)
        self.label_5.setGeometry(QtCore.QRect(260, 10, 61, 51))
        self.label_5.setStyleSheet("image:url(:/icon_excluir/icons/excluir.png)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(formCliente)
        self.label_6.setGeometry(QtCore.QRect(460, 10, 61, 51))
        self.label_6.setStyleSheet("image:url(:/icon_retornar/icons/retornar.png)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(formCliente)
        QtCore.QMetaObject.connectSlotsByName(formCliente)

    def retranslateUi(self, formCliente):
        _translate = QtCore.QCoreApplication.translate
        formCliente.setWindowTitle(_translate("formCliente", "Form"))
        item = self.tb_cliente.horizontalHeaderItem(0)
        item.setText(_translate("formCliente", "Id"))
        item = self.tb_cliente.horizontalHeaderItem(1)
        item.setText(_translate("formCliente", "Nome"))
        item = self.tb_cliente.horizontalHeaderItem(2)
        item.setText(_translate("formCliente", "Telefone"))
        item = self.tb_cliente.horizontalHeaderItem(3)
        item.setText(_translate("formCliente", "Cidade"))
        self.nome_cliente.setText(_translate("formCliente", "Nome Cliente:"))
import icon_adicionar_rc
import icon_alterar_rc
import icon_consultar_rc
import icon_excluir_rc
import icon_geral_rc
import icon_pesquisar_rc
import icon_retornar_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formCliente = QtWidgets.QWidget()
    ui = Ui_formCliente()
    ui.setupUi(formCliente)
    formCliente.show()
    sys.exit(app.exec_())
