# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dadosCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import mysql.connector
import pandas as pd

from PyQt5 import QtCore, QtGui, QtWidgets

#IMPORT TELAS

from form_ErroMensagem import Ui_Form

### IMPORT SISTEMA



### IMPORT Variaveis de controle
import variaveisControle

### conexao com o banco de dados
host = variaveisControle.host
user = variaveisControle.user
password = variaveisControle.password
database = variaveisControle.database

class Ui_form_dadosCliente(object):
    def setupUi(self, form_dadosCliente):
        form_dadosCliente.setObjectName("form_dadosCliente")
        form_dadosCliente.resize(400, 301)
        self.lb_nome = QtWidgets.QLabel(form_dadosCliente)
        self.lb_nome.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.lb_nome.setObjectName("lb_nome")
        self.txt_nome = QtWidgets.QLineEdit(form_dadosCliente)
        self.txt_nome.setGeometry(QtCore.QRect(80, 50, 251, 20))
        self.txt_nome.setObjectName("txt_nome")
        self.lb_telefone = QtWidgets.QLabel(form_dadosCliente)
        self.lb_telefone.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.lb_telefone.setObjectName("lb_telefone")
        self.txt_telefone = QtWidgets.QLineEdit(form_dadosCliente)
        self.txt_telefone.setGeometry(QtCore.QRect(80, 90, 251, 20))
        self.txt_telefone.setObjectName("txt_telefone")
        self.lb_cidade = QtWidgets.QLabel(form_dadosCliente)
        self.lb_cidade.setGeometry(QtCore.QRect(20, 130, 47, 13))
        self.lb_cidade.setObjectName("lb_cidade")
        self.txt_cidade = QtWidgets.QLineEdit(form_dadosCliente)
        self.txt_cidade.setGeometry(QtCore.QRect(80, 130, 251, 20))
        self.txt_cidade.setObjectName("txt_cidade")
        self.bt_cancelar = QtWidgets.QPushButton(form_dadosCliente)
        self.bt_cancelar.setGeometry(QtCore.QRect(80, 180, 81, 81))
        self.bt_cancelar.setText("")
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.label_6 = QtWidgets.QLabel(form_dadosCliente)
        self.label_6.setGeometry(QtCore.QRect(90, 190, 61, 51))
        self.label_6.setStyleSheet("image:url(:/icon_cancelar/icons/cancelar.png)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.bt_cadastrar = QtWidgets.QPushButton(form_dadosCliente)
        self.bt_cadastrar.setGeometry(QtCore.QRect(240, 180, 81, 81))
        self.bt_cadastrar.setText("")
        self.bt_cadastrar.setObjectName("bt_cadastrar")
        self.label_7 = QtWidgets.QLabel(form_dadosCliente)
        self.label_7.setGeometry(QtCore.QRect(250, 190, 61, 51))
        self.label_7.setStyleSheet("image:url(:/icon_cadastrar/icons/cadastrar.png)")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(form_dadosCliente)
        QtCore.QMetaObject.connectSlotsByName(form_dadosCliente)

    def retranslateUi(self, form_dadosCliente):
        _translate = QtCore.QCoreApplication.translate
        form_dadosCliente.setWindowTitle(_translate("form_dadosCliente", "Form"))
        self.lb_nome.setText(_translate("form_dadosCliente", "Nome:"))
        self.lb_telefone.setText(_translate("form_dadosCliente", "Telefone:"))
        self.lb_cidade.setText(_translate("form_dadosCliente", "Cidade:"))

##### BOTÕES SISTEMA #######
        self.bt_cancelar.clicked.connect(lambda: self.sairTela(form_dadosCliente))
        if variaveisControle.tipoTelaDadosCliente == "incluir":
            self.bt_cadastrar.clicked.connect(self.cadastrarCliente)
        if variaveisControle.tipoTelaDadosCliente == "alterar":
            self.bt_cadastrar.clicked.connect(self.alterarCliente)
        ### condições da tela
        #Tipo da Tela
        ##Tela incluir
        if variaveisControle.tipoTelaDadosCliente == 'incluir':
            print("Vraiaveis de controle:", variaveisControle.tipoTelaDadosCliente)
            self.txt_nome.setEnabled(True)
            self.txt_telefone.setEnabled(True)
            self.txt_cidade.setEnabled(True)
            self.bt_cadastrar.setEnabled(True)
        elif variaveisControle.tipoTelaDadosCliente == 'consultar':
            print("Vraiaveis de controle:", variaveisControle.tipoTelaDadosCliente)
            self.txt_nome.setEnabled(False)
            self.txt_telefone.setEnabled(False)
            self.txt_cidade.setEnabled(False)
            self.bt_cadastrar.setEnabled(False)
            #conexao com banco de dados
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database
            )
            mycursor = mydb.cursor()    
            consulta_sql = "SELECT * FROM cliente WHERE IdCliente = '" + variaveisControle.idConsulta + "'" 
            mycursor.execute(consulta_sql)
            myresult = mycursor.fetchall()
            mycursor.close()
            #converte resultado db para dataframe
            df = pd.DataFrame(myresult, columns=['ID','Nome','Telefone','Cidade'])
            nomeCliente = df['Nome'][0]
            telefoneCliente = df['Telefone'][0]
            cidadeCliente = df['Cidade'][0]

            # seta informações
            self.txt_nome.setText(nomeCliente)
            self.txt_telefone.setText(telefoneCliente)
            self.txt_cidade.setText(cidadeCliente)

        elif variaveisControle.tipoTelaDadosCliente == 'alterar':
            print("Vraiaveis de controle:", variaveisControle.tipoTelaDadosCliente)
            self.txt_nome.setEnabled(True)
            self.txt_telefone.setEnabled(True)
            self.txt_cidade.setEnabled(True)
            self.bt_cadastrar.setEnabled(True)
            #conexao com banco de dados
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database
            )
            mycursor = mydb.cursor()    
            consulta_sql = "SELECT * FROM cliente WHERE IdCliente = '" + variaveisControle.idConsulta + "'" 
            mycursor.execute(consulta_sql)
            myresult = mycursor.fetchall()
            mycursor.close()
            #converte resultado db para dataframe
            df = pd.DataFrame(myresult, columns=['ID','Nome','Telefone','Cidade'])
            nomeCliente = df['Nome'][0]
            telefoneCliente = df['Telefone'][0]
            cidadeCliente = df['Cidade'][0]

            # seta informações
            self.txt_nome.setText(nomeCliente)
            self.txt_telefone.setText(telefoneCliente)
            self.txt_cidade.setText(cidadeCliente)


        
###### FUNÇÕES SISTEMA ######

## SAIR da TELA
    def sairTela(self, form_dadosCliente):
        variaveisControle.tipoTelaDadosCliente = ""
        form_dadosCliente.close()
## CADASTRAR CLIENTE

    def cadastrarCliente(self):        
        
        nome_cliente = self.txt_nome.text()
        telefone = self.txt_telefone.text()
        cidade = self.txt_cidade.text()

        if nome_cliente != "":         
            
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database
            )

            mycursor = mydb.cursor()   

            sql = "INSERT INTO cliente (Nome, Telefone, Cidade) VALUES(%s, %s,%s)"
            val = (nome_cliente,telefone,cidade)

            mycursor.execute(sql,val)
            mydb.commit()

            print(mycursor.rowcount, ' record(s) inserted')
            mycursor.close()

            self.txt_nome.setText("")
            self.txt_telefone.setText("")
            self.txt_cidade.setText("")
        else:
            self.Form = QtWidgets.QWidget()
            self.ui = Ui_Form()
            self.ui.setupUi(self.Form)
            self.Form.show()
           
            #print("Preencher campo nome")
        

## Alterar CLIENTE

    def alterarCliente(self):        
        
        nome_cliente = self.txt_nome.text()
        telefone = self.txt_telefone.text()
        cidade = self.txt_cidade.text()

        if nome_cliente != "":         
            
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database
            )

            mycursor = mydb.cursor()   

            sql = "UPDATE cliente SET Nome ='" + nome_cliente + "', Telefone= '" + telefone + "', Cidade = '" + cidade + "' WHERE IdCliente = '" + variaveisControle.idConsulta + "'"  
            mycursor.execute(sql)
            mydb.commit()

            print(mycursor.rowcount, ' record(s) altered')
            mycursor.close()
           
            
          
        else:
            self.Form = QtWidgets.QWidget()
            self.ui = Ui_Form()
            self.ui.setupUi(self.Form)
            self.Form.show()
           
            #print("Preencher campo nome")
           


# Imagens do sistema
import icon_cadastrar
import icon_cancelar


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_dadosCliente = QtWidgets.QWidget()
    ui = Ui_form_dadosCliente()
    ui.setupUi(form_dadosCliente)
    form_dadosCliente.show()
    sys.exit(app.exec_())
