# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dadosCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_dadosCliente(object):
    def setupUi(self, form_dadosCliente):
        form_dadosCliente.setObjectName("form_dadosCliente")
        form_dadosCliente.resize(400, 301)
        self.lb_nome = QtWidgets.QLabel(form_dadosCliente)
        self.lb_nome.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.lb_nome.setObjectName("lb_nome")
        self.txt_nome = QtWidgets.QLineEdit(form_dadosCliente)
        self.txt_nome.setGeometry(QtCore.QRect(80, 50, 251, 20))
        self.txt_nome.setObjectName("txt_nome")
        self.lb_telefone = QtWidgets.QLabel(form_dadosCliente)
        self.lb_telefone.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.lb_telefone.setObjectName("lb_telefone")
        self.txt_telefone = QtWidgets.QLineEdit(form_dadosCliente)
        self.txt_telefone.setGeometry(QtCore.QRect(80, 90, 251, 20))
        self.txt_telefone.setObjectName("txt_telefone")
        self.lb_cidade = QtWidgets.QLabel(form_dadosCliente)
        self.lb_cidade.setGeometry(QtCore.QRect(20, 130, 47, 13))
        self.lb_cidade.setObjectName("lb_cidade")
        self.txt_cidade = QtWidgets.QLineEdit(form_dadosCliente)
        self.txt_cidade.setGeometry(QtCore.QRect(80, 130, 251, 20))
        self.txt_cidade.setObjectName("txt_cidade")
        self.bt_cancelar = QtWidgets.QPushButton(form_dadosCliente)
        self.bt_cancelar.setGeometry(QtCore.QRect(80, 180, 81, 81))
        self.bt_cancelar.setText("")
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.label_6 = QtWidgets.QLabel(form_dadosCliente)
        self.label_6.setGeometry(QtCore.QRect(90, 190, 61, 51))
        self.label_6.setStyleSheet("image:url(:/icon_cancelar/icons/cancelar.png)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.bt_cadastrar = QtWidgets.QPushButton(form_dadosCliente)
        self.bt_cadastrar.setGeometry(QtCore.QRect(240, 180, 81, 81))
        self.bt_cadastrar.setText("")
        self.bt_cadastrar.setObjectName("bt_cadastrar")
        self.label_7 = QtWidgets.QLabel(form_dadosCliente)
        self.label_7.setGeometry(QtCore.QRect(250, 190, 61, 51))
        self.label_7.setStyleSheet("image:url(:/icon_cadastrar/icons/cadastrar.png)")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(form_dadosCliente)
        QtCore.QMetaObject.connectSlotsByName(form_dadosCliente)

    def retranslateUi(self, form_dadosCliente):
        _translate = QtCore.QCoreApplication.translate
        form_dadosCliente.setWindowTitle(_translate("form_dadosCliente", "Form"))
        self.lb_nome.setText(_translate("form_dadosCliente", "Nome:"))
        self.lb_telefone.setText(_translate("form_dadosCliente", "Telefone:"))
        self.lb_cidade.setText(_translate("form_dadosCliente", "Cidade:"))
import icon_cadastrar_rc
import icon_cancelar_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_dadosCliente = QtWidgets.QWidget()
    ui = Ui_form_dadosCliente()
    ui.setupUi(form_dadosCliente)
    form_dadosCliente.show()
    sys.exit(app.exec_())
